gcloud ml-engine jobs submit training job_hp_14_6 ^
	--job-dir gs://chiron-data-fred/output/job_hp_14_6 ^
	--runtime-version 1.2 ^
	--module-name trainer.task ^
	--package-path keras/trainer/ ^
	--region us-east1 ^
	--config config.yaml ^
	-- ^
	--train-input-num 200000 ^
	--validate-input-num 50000 ^
	--eval-input-num 100000 ^
	--num-epochs 1000000 ^
	--eval-batch-size 500 ^
	--eval-frequency 50 ^
	--eval-batch-size 500 ^
	--verbose 2 ^
	--first-layer-dropout-rate 0.2 ^
	--dropout-rate-scale-factor 0.9
