gcloud ml-engine local train \
	--job-dir output \
	--module-name trainer.task \
	--package-path keras/trainer/ \
	-- \
	--train-input-num 2000 \
	--validate-input-num 500 \
	--eval-input-num 1000 \
	--first-layer-dropout-rate 0.2 \
	--dropout-rate-scale-factor 0.9 \
	--num-epochs 1000 \
	--early-stop-patience 10 \
	--train-batch-size 300 \
	--first-layer-size 100 \
	--num-layers 6 \
	--scale-factor 0.8 \
	--checkpoint-epochs 20 \
	--eval-frequency 20 \
	--eval-batch-size 500 \
	--eval-num-epochs 20 \
	--verbose 1
